import type { Metadata } from "next";
import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from "@clerk/nextjs";
 import { dark } from '@clerk/ui/themes'
import Header from "@/components/Header";
import Footer from "@/components/footer";
const lora =Lora({
  subsets : ["latin"],
  weight : ['400','500'],
  style : ["normal","italic"],
  variable : "--font-serif"
});


const dmSans =DM_Sans({
  subsets : ["latin"],
  weight : ['300','400','500','600'],
  variable : "--font-sans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{
      theme : dark,
    }}>
    <html
      lang="en"
      suppressHydrationWarning
    >
      <body className={`${lora.variable} ${dmSans.variable} font-sans`}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="min-h-screen">
              <Header/>
              {children}
            </main>
            <Footer/>
          </ThemeProvider>
        {/* {Header} */}
        {/* Footer */}
      </body>
    </html>
    </ClerkProvider>
  );
}
